services:
  database:
    image: "postgres:16.0-alpine3.18"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=local_password
      - POSTGRES_DB=edu_blog_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: